[project]
name = "mini-dpvo"
version = "0.1.0"
description = "Add a short description here"
authors = ["pablovela5620 <pablovela5620@gmail.com>"]
channels = ["nvidia/label/cuda-11.8.0", "nvidia", "conda-forge", "pytorch", "pyg"]
platforms = ["linux-64"]

[system-requirements]
libc = { family="glibc", version="2.31" }

[tasks]
download-model = """
    test -e checkpoints/dpvo.pth
    || (
        wget https://www.dropbox.com/s/nap0u8zslspdwm4/models.zip 
        && unzip models.zip -d checkpoints
        && rm -r models.zip
       )
"""
download-dpvo-data = """
    test -e data/movies/IMG_0492.MOV
    || (
        wget https://www.dropbox.com/s/7030y0mdl6efteg/movies.zip -P data/ 
        && unzip data/movies.zip -d data/
        && rm -r data/movies.zip
       )
"""

download-iphone-data = """
    test -e data/iphone/pool.MOV
    || (
        huggingface-cli download pablovela5620/dpvo-example-data pool.MOV --repo-type dataset --local-dir data/iphone/
    )
"""

post-install = {cmd="python -m pip install -e .", depends_on=["download-model", "download-dpvo-data", "download-iphone-data"], outputs=["cuda_ba.cpython-311-x86_64-linux-gnu.so"]}
rr-viewer = "rerun --memory-limit 50% --drop-at-latency 500ms"

demo = """
python tools/demo.py --imagedir data/movies/IMG_0493.MOV --calib data/calib/iphone.txt --config config/fast.yaml
"""
app = {cmd="python tools/app.py", depends_on=["post-install"]}

[dependencies]
python = "3.11.*"
pip = ">=24.0,<25"
cuda = {version = "*", channel="nvidia/label/cuda-11.8.0"}
pytorch-cuda = {version = "11.8.*", channel="pytorch"}
pytorch = {version = ">=2.2.0,<2.3", channel="pytorch"}
torchvision = {version = ">=0.17.0,<0.18", channel="pytorch"}
plyfile = ">=1.0.3,<1.1"
pytorch-scatter = {version="*", channel="pyg"}
matplotlib = ">=3.8.4,<3.9"
yacs = ">=0.1.8,<0.2"
jaxtyping = ">=0.2.28,<0.3"
icecream = ">=2.1.3,<2.2"
eigen = ">=3.4.0,<3.5"
rerun-sdk = ">=0.16.1"
tyro = ">=0.8.4,<0.9"

[pypi-dependencies]
opencv-python = ">=4.9.0.80"
evo = ">=1.28.0"
mini-dust3r = "*"
gradio-rerun = ">=0.0.3"
mmcv = "*"
yt-dlp = "*"
gradio = ">=4.36.0"
